<a href="https://colab.research.google.com/github/jaossandon/ENSO/blob/main/nparray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase: Tipos de datos en Python y NumPy (`np.array`)

## Objetivos de la clase

- Reconocer los tipos de datos básicos en Python: `int`, `float`, `str`, `bool`.
- Entender qué son las colecciones básicas: `list` y `tuple`.
- Comprender qué es NumPy y para qué se usa.
- Crear y manipular arreglos `np.array` en 1 y 2 dimensiones.

---


## 1. Tipos de datos básicos en Python

Antes de programar, es importante conocer los tipos de datos más fundamentales que utiliza Python. Estos tipos representan la forma en que el lenguaje guarda y entiende la información.

### `int` — Números enteros
Corresponden a números sin parte decimal.
**Ejemplos:**  
- 10  
- -5  
- 0  

### `float` — Números decimales
Son números que incluyen parte decimal.  
**Ejemplos:**  
- 3.14  
- -2.5  
- 10.0  

### `str` — Cadenas de texto
Representan texto. Se escriben siempre entre comillas.  
**Ejemplos:**  
- `"Hola"`  
- `"Python"`  
- `"123"` (esto es texto, no un número)

### `bool` — Valores lógicos
Indican verdadero o falso.  
**Ejemplos:**  
- `True`  
- `False`

En la siguiente celda veremos cómo se escriben estos valores en Python, pero por ahora es suficiente con entender qué representan.


In [4]:
# Ejemplos básicos de tuplas en Python

# Lista escrita con corchetes
mi_lista = [10, 20, 30]
mi_lista



[10, 20, 30]

In [5]:
# Ejemplos básicos de listas en Python

# Tupla escrita con paréntesis redondos
mi_tupla = (1, 2, 3)
mi_tupla


(1, 2, 3)

## 3. ¿Qué es NumPy?

Antes de trabajar con arreglos numéricos más avanzados, necesitamos conocer **NumPy**, que es una de las bibliotecas más importantes de Python para el trabajo científico y de datos.

**NumPy** significa *Numerical Python* y nos permite:

- Trabajar con arreglos numéricos de manera eficiente.
- Realizar cálculos matemáticos de forma muy rápida.
- Manejar vectores, matrices y datos en varias dimensiones.

La estructura principal que utiliza NumPy para almacenar datos se llama **`np.array`**, y será el foco de las próximas celdas.

En la siguiente celda importaremos la biblioteca para comenzar a usarla.


In [6]:
# Importar la biblioteca NumPy
import numpy as np


## 4. ¿Qué es un `np.array`?

El objeto principal que utiliza NumPy para trabajar con datos se llama **`np.array`**.

Un `np.array` es una estructura que permite:

- Guardar varios valores numéricos en una sola variable.
- Organizar esos valores en distintas formas: como un vector, como una matriz o en más dimensiones.
- Realizar operaciones matemáticas de manera rápida y eficiente.

A diferencia de las listas de Python, los `np.array` están pensados específicamente para cálculos numéricos, por lo que son mucho más eficientes cuando se trabaja con grandes cantidades de datos.

En la siguiente celda veremos cómo crear nuestro primer `np.array`.


## 4. Parámetros de la función `np.array()`

La función `np.array()` es la forma principal de crear arreglos en NumPy.  
Su estructura general es:

array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0, like=None)

A continuación se explica cada uno de sus parámetros:

---

### **1. `object`**
Es el dato de entrada que se convertirá en un arreglo.  
Puede ser una lista, una tupla, otra matriz, o un `np.array`.  
Este es el único parámetro obligatorio.

---

### **2. `dtype`**
Define el tipo de dato de los elementos del arreglo.  
Ejemplos posibles:
- `int32`
- `float64`
- `bool`
- `object`

Si no se especifica, NumPy elige uno automáticamente.

---

### **3. `copy`**
Indica si debe hacerse una copia de los datos.
- `True` → crea una copia (por defecto)
- `False` → intenta evitar copiar

En la mayoría de los casos se deja en `True`.

---

### **4. `order`**
Define el orden en que se organizan los datos en memoria:
- `'C'` → por filas
- `'F'` → por columnas
- `'K'` → conserva el orden del objeto de entrada (valor por defecto)

---

### **5. `subok`**
Indica si se permiten subclases de `ndarray`.
- `False` → siempre devuelve un `np.ndarray` (por defecto)
- `True` → conserva subclases si existen

Es un parámetro avanzado.

---

### **6. `ndmin`**
Especifica el **número mínimo de dimensiones** del arreglo.

Ejemplos:
- `ndmin=1` → asegura un vector
- `ndmin=2` → asegura una matriz
- `ndmin=3` → crea una dimensión adicional

---

### **7. `like`**
Indica que el nuevo arreglo debe imitar la estructura de otro objeto.  
Se usa muy poco.

---

## Resumen
`np.array()` permite controlar:
- el dato de entrada  
- el tipo de dato  
- si se copia o no  
- el orden de memoria  
- las dimensiones mínimas  
- si se permiten subclases  
- si debe imitar otro objeto  

En la siguiente celda crearemos un arreglo usando algunos de estos parámetros.


In [8]:
# Ejemplo 1: Crear un np.array básico a partir de una lista
# Aqui transformamos la lista [1, 2, 3] en un arreglo de NumPy.

import numpy as np

a1 = np.array([1, 2, 3])
a1    # Se muestra automáticamente


array([1, 2, 3])

In [9]:
# Ejemplo 2: Crear un np.array indicando el tipo de dato (dtype)
# En este caso convertimos los valores a float (números decimales).

import numpy as np

a2 = np.array([1, 2, 3], dtype=np.float64)
a2


array([1., 2., 3.])

In [10]:
# Ejemplo 3: Usar ndmin para obligar un mínimo de dimensiones
# ndmin=2 transforma la lista en una matriz de 1 fila y 3 columnas.

import numpy as np

a3 = np.array([1, 2, 3], ndmin=2)
a3


array([[1, 2, 3]])

In [11]:
# Ejemplo 4: Crear un np.array con orden en memoria tipo 'C' (por filas)
# Esto significa que el arreglo se almacena fila por fila.

import numpy as np

a4 = np.array([[1, 2], [3, 4]], order='C')
a4


array([[1, 2],
       [3, 4]])

In [12]:
# Ejemplo 5: Crear un np.array con orden en memoria tipo 'F' (por columnas)
# Esto significa que se almacena columna por columna.

import numpy as np

a5 = np.array([[1, 2], [3, 4]], order='F')
a5


array([[1, 2],
       [3, 4]])

In [13]:
# Ejemplo 6: Crear un np.array con dtype=object
# Esto permite mezclar distintos tipos de datos dentro del mismo arreglo.

import numpy as np

a6 = np.array([1, "hola", 3.5], dtype=object)
a6


array([1, 'hola', 3.5], dtype=object)

In [14]:
# Ejemplo 7: Usar el parámetro copy para crear una copia del objeto de entrada
# Normalmente copy=True, pero este ejemplo muestra cómo se usa.

import numpy as np

a7 = np.array([10, 20, 30], copy=True)
a7


array([10, 20, 30])

In [15]:
# Ejemplo 8: Forzar tres dimensiones con ndmin=3
# Esto envuelve los datos en dos niveles extras de corchetes.

import numpy as np

a8 = np.array([1, 2, 3], ndmin=3)
a8


array([[[1, 2, 3]]])